### ISSUE TITLE
Suggested change in the points system

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-HW1#106]
Seeing that we are lacking in the comments and issues (only 74 issues when we need 120 and 250 comments, 100+ being @laserlab 's, when we need 375+ from students), may I suggest that we could change the points system somehow?

maybe comments that are longer could be worth more points? maybe comments that solve the issue could be worth more? or maybe issues that are more important could be worth more? Or if anybody else has an idea?

**Comment by iamtomato761** [comment]
I agree that a change is needed. It's important to note, however, that this was the first homework, so people aren't used to commenting so much. It seems like the number of issues to open and conversations/comments to add is a reasonable goal for future homework, but I agree that at least for the first one, this may have been too far of a goal for several people.

**Comment by iamtomato761** [comment]
> maybe comments that are longer could be worth more points? maybe comments that solve the issue could be worth more? or maybe issues that are more important could be worth more? Or if anybody else has an idea?

I'm not sure these ideas would make things easier. It would be tougher to grade, though much of the grading is subjective anyway. The qualitative grading for task completion is acceptable because we can see PR comments before the deadline to know if we need to do more. I'm not sure how the quality of comments and issues can be tracked. 

Some ideas:

- Maybe high engagement of our issues, measured by the number of comments, can provide bonus points to fill in the gaps (so it isn't required) since people can be losing points in different aspects of participation. This would encourage more thought-provoking questions, conceptual discussions, and a space to suggest multiple solutions.
- On the other side of that, we can also somehow get more points for commenting on issues with less engagement? Encourage bringing engagement to it?
- Another qualitative idea is submitting a brief report on what we believe our contributions have been, an analysis of the skills we feel like we individually built on, and ideas on how the project could have run smoother- an overall reflection.

**Comment by jkblc** [comment]
You have a good point, as I am struggling to come up with relevant issues to open. As it seems there is no reason for the code to actually run on a quantum computer to complete the homework, I am just asking random questions in issues.

**Comment by laserlab** [comment]
@jkblc Instead of random questions why don’t you open issue that make the code runnable?

**Comment by p-pxmpo** [comment]
thank you
