### ISSUE TITLE
Formatting question.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW1#19]
For the Markdown file on the background of the problem what format is required for the citations?

**Comment by laserlab** [comment]
There is no good answer since there is no common way to do it. Old schoolers like me like bibtex extensions for markdown, but it is probably worth looking into this here:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by laserlab** [comment]
If someone would like to use this to support the others it would be a great homework task

**Comment by kylemasc917** [comment]
I can go forward using this and the APA format thank you.
